# Pynab PR labels
'Documentation':
  - changed-files:
    - any-glob-to-any-file:
      - _config.yml
      - docs/**/*
      - CONTRIBUTING.md
      - index.md
      - LICENSE
      - PROTOCOL.md
      - README.md

'Environment':
  - changed-files:
    - any-glob-to-any-file:
      - .github/*
      - .github/**/*
      - .coveragerc
      - .editorconfig
      - .flake8
      - .gitignore
      - .isort.cfg
      - .pep8speaks.yml
      - .pre-commit-config.yaml
      - pyproject.toml
      - pytest.ini

'Setup':
  - changed-files:
    - any-glob-to-any-file:
      - install.sh
      - manage.py
      - requirements.txt
      - setup
      - upgrade.sh

'Docker environment':
  - changed-files:
    - any-glob-to-any-file:
      - Docker/**

'Service: 8ball':
  - changed-files:
    - any-glob-to-any-file:
      - nab8balld/**

'Service: Air Quality':
  - changed-files:
    - any-glob-to-any-file:
      - nabairqualityd/**

'Service: Book':
  - changed-files:
    - any-glob-to-any-file:
      - nabbookd/**

'boot':
  - changed-files:
    - any-glob-to-any-file:
      - nabboot/**

'Service: Clock':
  - changed-files:
    - any-glob-to-any-file:
      - nabclockd/**

'common':
  - changed-files:
    - any-glob-to-any-file:
      - nabcommon/**

'Service : Nab':
  - changed-files:
    - any-glob-to-any-file:
      - nabd/**

'Service: Mastodon':
  - changed-files:
    - any-glob-to-any-file:
      - nabmastodond/**

'Service: Surprise':
  - changed-files:
    - any-glob-to-any-file:
      - nabsurprised/**

'Service: Tai chi':
  - changed-files:
    - any-glob-to-any-file:
      - nabtaichid/**

'Service: Weather':
  - changed-files:
    - any-glob-to-any-file:
      - nabweatherd/**

'Service: IFTTT':
  - changed-files:
    - any-glob-to-any-file:
      - nabiftttd/**

'Service: Radio':
  - changed-files:
    - any-glob-to-any-file:
      - nabradio/**

'Service: Web hook':
  - changed-files:
    - any-glob-to-any-file:
      - nabwebhook/**

'web':
  - changed-files:
    - any-glob-to-any-file:
      - nabweb/**

'Translations':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.po'
