name: 🏗️  Build
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
  workflow_dispatch:
jobs:
  create_image:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [zero_raspios, zero2_64_raspios]
        include:
        - target: zero_raspios
          cpu: arm1176
          cpu_info: cpuinfo/raspberrypi_zero_w
          base_image: raspios_lite:2023-05-03
        - target: zero2_64_raspios
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
          base_image: raspios_lite_arm64:2023-05-03
    steps:
      - name: Checkout pynab
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Cache apt + build dirs
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/apt
            /var/cache/apt
            /opt/pynab/.cache
          key: >
            ${{ runner.os }}-${{ matrix.target }}-${{ matrix.base_image }}-${{ hashFiles('**/*.sh', '**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-${{ matrix.base_image }}

      - name: Define the image name
        id: image_and_branch_name
        run: |
          REF="${{ inputs.ref }}"

          # always normalize FIRST
          SAFE_REF="${REF//\//-}"

          if [[ "$REF" == refs/tags/* ]]; then
            NAME="${REF#refs/tags/}"
            SAFE_NAME="${NAME//\//-}"

            echo "LOCAL_BRANCH=$NAME" >> $GITHUB_OUTPUT
            echo "RELEASE_NAME=$NAME" >> $GITHUB_OUTPUT
            echo "IMAGE_NAME_SUFFIX=$SAFE_NAME-${{ matrix.target }}" >> $GITHUB_OUTPUT
            echo "CLONE_RELEASE=yes" >> $GITHUB_OUTPUT

          elif [[ "$REF" == refs/heads/releng ]]; then
            echo "LOCAL_BRANCH=releng" >> $GITHUB_OUTPUT
            echo "RELEASE_NAME=releng" >> $GITHUB_OUTPUT
            echo "IMAGE_NAME_SUFFIX=releng-${{ matrix.target }}" >> $GITHUB_OUTPUT
            echo "CLONE_RELEASE=yes" >> $GITHUB_OUTPUT

          elif [[ "$REF" == refs/heads/* ]]; then
            NAME="${REF#refs/heads/}"
            SAFE_NAME="${NAME//\//-}"

            echo "LOCAL_BRANCH=$NAME" >> $GITHUB_OUTPUT
            echo "RELEASE_NAME=$NAME" >> $GITHUB_OUTPUT
            echo "IMAGE_NAME_SUFFIX=$SAFE_NAME-${{ matrix.target }}" >> $GITHUB_OUTPUT
            echo "CLONE_RELEASE=yes" >> $GITHUB_OUTPUT

          else
            echo "LOCAL_BRANCH=$REF" >> $GITHUB_OUTPUT
            echo "IMAGE_NAME_SUFFIX=$SAFE_REF-${{ matrix.target }}" >> $GITHUB_OUTPUT
            echo "CLONE_RELEASE=no" >> $GITHUB_OUTPUT
          fi

      - name: Create a release image in chroot environment
        uses: mtouzot/arm-runner-action@v2.6.6
        id: arm_runner_install
        with:
          image_additional_mb: 4096
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          optimize_image: yes
          copy_repository_path: /opt/pynab
          commands: |
            # Disable IPv6 in case it is configured but does not work
            ping6 -c 1 www.ietf.org || sudo sysctl -w net.ipv6.conf.eth0.disable_ipv6=1
            sudo apt-get update -y --allow-releaseinfo-change
            echo GITHUB_BRANCH=${{ steps.image_and_branch_name.outputs.LOCAL_BRANCH }}
            echo GITHUB_REPOSITORY=${{ github.repository }}
            cd /tmp
            sudo cp -p /opt/pynab/setup /tmp/setup
            if [ ${{ steps.image_and_branch_name.outputs.CLONE_RELEASE }} = "yes" ]; then
                sudo rm -rf /opt/pynab
            else
                sudo useradd tagtagtag -u 1000 -g 1000 -m || true
                sudo chown -hR 1000:1000 /opt/pynab
            fi
            if [ `uname -m` = 'armv6l' -o `uname -m` = 'armv7l' ]; then
                sudo GITHUB_BRANCH=${{ steps.image_and_branch_name.outputs.LOCAL_BRANCH }} GITHUB_REPOSITORY=${{ github.repository }} taskset -c 0 /bin/bash /tmp/setup ci-chroot
            else
                sudo GITHUB_BRANCH=${{ steps.image_and_branch_name.outputs.LOCAL_BRANCH }} GITHUB_REPOSITORY=${{ github.repository }} /bin/bash /tmp/setup ci-chroot
            fi
            sudo rm /tmp/setup
            sudo apt-get autoremove --purge -y
            sudo apt-get clean

      - name: Compress the release image
        run: |
          mv ${{ steps.arm_runner_install.outputs.image }} pynab-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img
          sudo xz -T 0 -v pynab-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img

      - name: Upload the image artifact
        uses: actions/upload-artifact@v7
        with:
          name: pynab-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img.xz
          path: pynab-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img.xz
          if-no-files-found: error
          retention-days: 1

