name: 👷 CI/CD

on:
  push:
    branches: ['**']   # 🔥 toutes les branches
  pull_request:

jobs:

  # =========================
  # 1. LINT (GLOBAL CI)
  # =========================
  lint:
    uses: ./.github/workflows/python-lint.yml

  # =========================
  # 2. TESTS (GLOBAL CI)
  # =========================
  tests:
    needs: lint
    uses: ./.github/workflows/tests.yml

  # =========================
  # 3. CodeQL (GLOBAL CI)
  # =========================
  codeql:
    needs: tests
    uses: ./.github/workflows/codeql.yml

  # =========================
  # 4. BUILD IMAGE (CONDITIONNÉ)
  # =========================
  build:
    needs: [tests, codeql]
    if: success() && github.event_name != 'pull_request'
    uses: ./.github/workflows/arm-runner.yml
    with:
      ref: ${{ github.ref }}


  # =========================
  # 5. SEMANTIC RELEASE (MAIN ONLY)
  # =========================
  semantic_release:
    needs: [tests, codeql]
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          npm install -g semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
